# Generated by Django 5.0.2 on 2024-12-04 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_a1dmin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='A1dmin',
        ),
    ]
