# Generated by Django 5.1.6 on 2025-03-02 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_delete_a1dmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='skill',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('free', 'Free'), ('busy', 'Busy'), ('on_leave', 'On Leave')], default='free', max_length=10),
        ),
    ]
