# Generated by Django 5.1.6 on 2025-03-04 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_admin_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='designation',
            field=models.CharField(choices=[('senior_developer', 'Senior Developer'), ('mid_developer', 'Mid Developer'), ('junior_developer', 'Junior Developer')], default='junior_developer', max_length=20),
        ),
    ]
