# Generated by Django 5.0.2 on 2024-12-02 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='projects', to='projects.task'),
        ),
        migrations.AlterField(
            model_name='project',
            name='teammembers',
            field=models.ManyToManyField(blank=True, related_name='projects', to='projects.teammember'),
        ),
    ]
