# Generated by Django 5.1.6 on 2025-03-04 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='designation',
            field=models.JSONField(default=list),
        ),
    ]
