# Generated by Django 5.1.6 on 2025-03-05 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_task_duedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='designation',
            field=models.CharField(max_length=50),
        ),
    ]
