# Generated by Django 5.1.6 on 2025-04-22 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_task_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='tasktype',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
